steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/gke-demo/gke-demo:$SHORT_SHA
    - .

# Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/gke-demo/gke-demo:$SHORT_SHA

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud secrets versions access latest \
        --secret=cloudbuild-ssh-key > /workspace/id_rsa

      gcloud secrets versions access latest \
        --secret=cloudbuild-ssh-pub > /workspace/id_rsa.pub

      chmod 600 /workspace/id_rsa
      chmod 644 /workspace/id_rsa.pub

# Deploy through Bastion
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud compute ssh bastion-vm \
      --zone=asia-south1-a \
      --ssh-key-file=/workspace/id_rsa \
      --tunnel-through-iap \
      --command="cd ~/gke-private-ingress && ./deploy.sh $SHORT_SHA"

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/gke-demo/gke-demo:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
