steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'app'
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/gke-demo/gke-demo:$SHORT_SHA
    - .

# Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/gke-demo/gke-demo:$SHORT_SHA

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/gke-demo/gke-demo:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
